[basics]
name    = "Alexander Obukhov"
label   = "Software Engineer"  # e.g. Web Developer
image   = ""  # URL (as per RFC 3986) to a image in JPEG or PNG format
email   = ""  # e.g. thomas@gmail.example.com
phone   = ""  # Phone numbers are stored as strings so use any format you like, e.g. 712-117-2923
url     = "https://sprql.space"  # URL (as per RFC 3986) to your website, e.g. personal homepage
summary = "Passionate programmer"  # Write a short 2-3 sentence biography about yourself


[basics.location]
address     = "Earth"  # To add multiple address lines, use \n. For example, 1234 Glücklichkeit Straße\nHinterhaus 5. Etage li.
postalCode  = ""
city        = ""
countryCode = ""  # code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN
region      = ""  # The general region where you live. Can be a US state, or a province, for instance.


# Specify any number of social networks that you participate in
[[basics.profiles]]
network  = "Github"  # e.g. Facebook or Twitter
username = "sprql"  # e.g. neutralthoughts
url      = "https://github.com/sprql"  # e.g. http://twitter.com/neutralthoughts


[[work]]
name        = ""  # e.g. Facebook
description = ""  # e.g. Social Media Company
position    = "Software Engineer"  # e.g. Software Engineer
url         = ""  # e.g. http://facebook.example.com
startDate   = ""  # ISO 8601 date standard e.g. 2014-06-29
endDate     = ""  # e.g. 2012-06-29
summary     = ""  # Give an overview of your responsibilities at the company
highlights  = []  # Specify multiple accomplishments, e.g. Increased profits by 20% from 2011-2012 through viral advertising


[[volunteer]]
organization = ""  # e.g. Facebook"
position     = ""  # e.g. Software Engineer"
url          = ""  # e.g. http://facebook.example.com"
startDate    = ""  # resume.json uses the ISO 8601 date standard e.g. 2014-06-29"
endDate      = ""  # e.g. 2012-06-29"
summary      = ""  # Give an overview of your responsibilities at the company"
highlights   = []  # Specify multiple accomplishments, e.g. Increased profits by 20% from 2011-2012 through viral advertising


[[education]]
institution = ""  # e.g. Massachusetts Institute of Technology
area        = "Computer Science"  # e.g. Arts
studyType   = ""  # e.g. Bachelor
startDate   = ""  # e.g. 2014-06-29
endDate     = ""  # e.g. 2012-06-29
gpa         = ""  # grade point average, e.g. 3.67/4.0
courses     = []  # List notable courses/subjects, e.g. H1302 - Introduction to American history


# Specify any awards you have received throughout your professional career
[[awards]]
title   = ""  # e.g. One of the 100 greatest minds of the century
date    = ""  # e.g. 1989-06-12
awarder = ""  # e.g. Time Magazine
summary = ""  # e.g. Received for my work with Quantum Physics


# Specify your publications through your career
[[publications]]
name        = ""  # e.g. The World Wide Web
publisher   = ""  # e.g. IEEE, Computer Magazine
releaseDate = ""  # e.g. 1990-08-01
url         = ""  # e.g. http://www.example.computer.org/csdl/mags/co/1996/10/rx069-abs.html
summary     = ""  # Short summary of publication. e.g. Discussion of the World Wide Web, HTTP, HTML.


# List out your professional skill-set
[[skills]]
name     = ""  # e.g. Web Development
level    = ""  # e.g. Master
keywords = ["Elixir", "Ruby", "JavaScript"]  # List some keywords pertaining to this skill

[[skills]]
name     = ""
level    = ""
keywords = [
  "Go",
  "Objective-C",
  "Swift"
]

[[skills]]
name     = ""
level    = ""
keywords = [
  "OTP",
  "Phoenix",
  "Ruby On Rails"
]

[[skills]]
name     = ""
level    = ""
keywords = [
  "PostgreSQL",
  "Redis"
]

[[skills]]
name     = ""
level    = ""
keywords = [
  "Docker",
  "Ansible"
]

[[skills]]
name     = ""
level    = ""
keywords = [
  "HTML",
  "CSS",
  "XSLT",
]


# List any other languages you speak
[[languages]]
language = "Russian"  # e.g. English, Spanish
fluency = "Native speaker"  # e.g. Fluent, Beginner

[[languages]]
language = "English"
fluency  = "Professional working proficiency"


[[interests]]
name     = "Music"  # e.g. Philosophy
keywords = []  # e.g. Friedrich Nietzsche


# List references you have received
[[references]]
name      = ""  # e.g. Timothy Cook
reference = "By request"  # e.g. Joe blogs was a great employee, who turned up to work at least once a week. He exceeded my expectations when it came to doing nothing.


# Specify career projects
[[projects]]
name        = "tomlresume"  # e.g. The World Wide Web
description = ""  # Short summary of project. e.g. Collated works of 2017.
highlights  = []  # Specify multiple features, e.g. Directs you close but not quite there
keywords    = []  # Specify special elements involved, e.g. AngularJS
startDate   = ""  # ISO 8601 date standard e.g. 2014-06-29
endDate     = ""  # e.g. 2012-06-29
url         = "https://github.com/sprql/tomlresume"  # e.g. http://www.computer.example.org/csdl/mags/co/1996/10/rx069-abs.html"
roles       = []  # Specify your role on this project or in company, e.g. Team Lead, Speaker, Writer
entity      = ""  # Specify the relevant company/entity affiliations e.g. 'corporationXYZ'"
type        = ""  # e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'


# The schema version and any other tooling configuration lives here
[meta]
canonical    = ""  # URL (as per RFC 3986) to latest version of this document
version      = ""  # A version field which follows semver - e.g. v1.0.0
lastModified = ""  # Using ISO 8601 with YYYY-MM-DDThh:mm:ss
